- name: Install java and zookeeper cluster for druid
  hosts: zookeeper
  become: yes
  roles:
    - {role: zookeeper-upgrade}
  # vars:
  #   zookeeper_group: "{{ groups['zookeeper'] }}"
  

# - name : Install graphite on druid
#   hosts: druid
#   become: yes
#   roles:
#     - {role: druid_graphite}

- name: Install role druid
  hosts: druid
  become: yes
  roles:
    - {role: druid-cluster, when: "'coordinator' in group_names", druid_role: 'coordinator', service: 'coordinator' }
    - {role: druid-cluster, when: "'overlord' in group_names", druid_role: 'overlord', service: 'overlord'}
    - {role: druid-cluster, when: "'broker' in group_names", druid_role: 'broker', service: 'broker'}
    - {role: druid-cluster, when: "'historical' in group_names", druid_role: 'historical', service: 'historical'}
    - {role: druid-cluster, when: "'middlemanager' in group_names", druid_role: 'middlemanager', service: 'middleManager' }

- hosts: druid
  gather_facts: yes
  become: yes
  roles:
    - druid-cluster